add_newline = false
command_timeout = 300

format = "$username$hostname$directory${env_var.python_venv}$git_branch$git_status$cmd_duration$character"

[directory]
fish_style_pwd_dir_length = 1
style = "blue"

[env_var.python_venv]
variable = "VIRTUAL_ENV_PROMPT"
format = "[($env_value)]($style) "
style = "bright-black"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "([$all_status]($style) )"

[username]
show_always = false
style_user = "bright-green"
style_root = "red"
format = "[$user]($style)"

[hostname]
ssh_only = true
ssh_symbol = ""
format = "@[$hostname]($style) "
style = "yellow"

[cmd_duration]
min_time = 2000
format = "[took $duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[>](magenta)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](green)"
